name:                crimes-against-humanity
version:             0.1.0.0
github:              "enolive/crimes-against-humanity"
license:             MIT
author:              "Christoph Welcz"
maintainer:          "christoph@welcz.de"
copyright:           "2019 Christoph Welcz"
# synopsis: A new project for TDD with Haskell.
# description: crimes-against-humanity see README.md for further details.
# category: Other

extra-source-files:
- README.md
- package.yaml
- LICENSE.md

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  crimes-against-humanity-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crimes-against-humanity

tests:
  crimes-against-humanity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crimes-against-humanity
    - hspec
    - QuickCheck
